// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class table_inter_internshiplisting_companyasasa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_inter_internshiplisting_companyasasa));
        
        string IMigrationMetadata.Id
        {
            get { return "202405060724124_table_inter_internshiplisting_companyasasa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
